- id: prettier
  name: prettier
  entry: prettier --write --ignore-unknown
  language: node
  types: [text]
  stages: [pre-commit] # only run for 'pre-commit' hook and not 'commit-msg'
  additional_dependencies: ['prettier@3.7.4']
